steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'infra'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/policy-copilot/litellm:$SHORT_SHA', '-f', 'litellm.Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/policy-copilot/litellm:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'policy-copilot-litellm'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/policy-copilot/litellm:$SHORT_SHA'
      - '--region=asia-south1'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/policy-copilot/litellm:$SHORT_SHA'
